window.SHOP_PRODUCTS = [
  {
    id: 'tshirt-men',
    slug: 't-shirt-meski-classic',
    name: 'T-shirt klasyczny ExploRide męski',
    price: 45,
    summary: 'Wygodny krój, nadruk ExploRide i dostępne rozmiary S–XXL.',
    description:
      'Wygodny krój, logo na froncie oraz z tyłu i kod QR na prawym rękawie',
    longDescription: [
      'Nadruk: DTF',
      'Gramatura: 150 g/m²',
      'Rozmiary: XS, S, M, L, XL, XXL',
      'Skład materiału: bawełna (100%)',
      'Rodzaj materiału: jersey',
      'Processing: szwy boczne',
      'Pielęgnacja: pranie do 40°C',
      'Certyfikaty: Fair Working Conditions',
      'OEKO-TEX® STANDARD 100',
      'Vegan',
      'Kolorystyka: czarna',
      'Krój: slim',
      'Dekolt: taśma wzmacniająca, okrągły',
      'Rękawy: krótki, wszyty (set in)',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: [
           'https://exploride.pl/sklep/photos/thirtclassicmodel.png',
      'https://exploride.pl/sklep/photos/tshirt-exploride-classic.jpg',
    'https://exploride.pl/sklep/photos/thirtclassic3.jpg'

    ],
    image: 'https://exploride.pl/sklep/photos/thirtclassicmodel.png',
    imageAlt: 'Wizualizacja koszulki męskiej ExploRide',
    imagePlaceholder: 'Placeholder zdjęcia',
    imageCaption: 'Przykładowa wizualizacja koszulki.',
    note: 'Dostępność i terminy wysyłki zostaną potwierdzone po złożeniu zamówienia przez formularz.',
  },
  {
    id: 'tshirt-women',
    slug: 't-shirt-damski-classic',
    name: 'T-shirt klasyczny ExploRide damski',
    price: 45,
  summary: 'Wygodny krój, nadruk ExploRide i dostępne rozmiary S–XXL.',
    description: 'Dopasowany krój, lekka bawełna i logo ExploRide – wygoda w kobiecym wydaniu.',
    longDescription: [
      'Nadruk: DTF',
      'Gramatura: 150 g/m²',
      'Rozmiary: XS, S, M, L, XL, XXL',
      'Skład materiału: bawełna (100%)',
      'Rodzaj materiału: jersey',
      'Processing: szwy boczne',
      'Pielęgnacja: pranie do 40°C',
      'Certyfikaty: Fair Working Conditions',
      'OEKO-TEX® STANDARD 100',
      'Vegan',
      'Kolorystyka: czarna',
      'Krój: slim',
      'Dekolt: taśma wzmacniająca, okrągły',
      'Rękawy: krótki, wszyty (set in)',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: [
       'https://exploride.pl/sklep/photos/thirtclassicmodelbaba.png',
       'https://exploride.pl/sklep/photos/tshirt-exploride-classic.jpg',
    'https://exploride.pl/sklep/photos/thirtclassic3.jpg',
    
    ],
    image:   'https://exploride.pl/sklep/photos/thirtclassicmodelbaba.png',
    imageAlt: 'Wizualizacja koszulki damskiej ExploRide',
    imagePlaceholder: 'Placeholder zdjęcia',
    imageCaption: 'Przykładowa wizualizacja koszulki.',
    note: 'Dostępność i terminy wysyłki zostaną potwierdzone po złożeniu zamówienia przez formularz.',
  },
 
  {
    id: 'calendar-2026',
    slug: 'kalendarz-2026',
    name: 'Kalendarz ExploRide Urbex 2026',
    price: 35,
    summary: '12 kadrów z wypraw urbexowych na każdy miesiąc.',
    description:
      'Kalendarz ścienny A4 ze spiralą pośrodku, zawierający autorskie zdjęcia opuszczonych miejsc uchwyconych podczas eksploracji urbexowych. Każdy miesiąc wzbogaciliśmy o krótkie opisy lokalizacji widocznych na fotografiach, a także o nietypowe święta i wydarzenia nawiązujące do urbexu, historii, architektury i zabytków. To wyjątkowe połączenie klimatycznych fotografii i ciekawostek dla miłośników opuszczonych miejsc oraz odkrywania zapomnianych historii.',
    sizes: [],
    images: [
  'https://exploride.pl/sklep/photos/kalendarz2026-1.jpg',
  'https://exploride.pl/sklep/photos/kalendarz2026-2.jpg',
    ],
    image: '',
    imageAlt: 'Okładka kalendarza ExploRide Urbex 2026',
    imagePlaceholder: 'Okładka kalendarza',
    imageCaption: 'Mocny urbexowy klimat na każdy miesiąc.',
    note: 'Wysyłka po potwierdzeniu dostępności – informacja w podsumowaniu zamówienia.',
  },

  {
    id: 'cap-exploride',
    slug: 'czapka-z-daszkiem-exploride',
    name: 'Czapka z daszkiem ExploRide',
    price: '??',
    summary: 'Produkt dostępny wkrótce',
    description: 'Produkt dostępny wkrótce. Placeholder opisu czapki z daszkiem ExploRide.',
    longDescription: [
      'Produkt dostępny wkrótce.',
      'Placeholder specyfikacji produktu.',
      'Placeholder informacji o materiałach i rozmiarach.',
    ],
    sizes: [],
    images: [],
    image: '',
    imageAlt: 'Produkt dostępny wkrótce',
    imagePlaceholder: 'WKRÓTCE',
    imageCaption: 'Produkt dostępny wkrótce.',
    note: 'Produkt dostępny wkrótce.',
  },
  {
    id: 'explosync',
    slug: 'explosync-plugin-do-adobe-premiere',
    name: '(Wkrótce) ExploSync - Plugin do Adobe Premiere',
    price: 45,
    available: false,
    summary: 'Automatyczna synchronizacja wielu nagrań wideo i audio na timeline. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Automatyczna synchronizacja wielu nagrań wideo i audio na timeline. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploSync automatycznie synchronizuje materiały z wielu kamer i rejestratorów dźwięku na podstawie ich ścieżek audio. Plugin pozwala szybko uporządkować nawet dużą liczbę klipów bez ręcznego przesuwania ich na timeline. Oferuje również precyzyjną korektę synchronizacji, gdy standardowe dopasowanie wymaga dodatkowego poprawienia. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploSync - plugin do Adobe Premiere', imagePlaceholder: 'ExploSync', imageCaption: 'Plugin do Adobe Premiere — wkrótce.',
    note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'explosubs', slug: 'explosubs-plugin-do-adobe-premiere', name: '(Wkrótce) ExploSubs - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Automatyczna transkrypcja nagrań w praktycznie każdym języku i tworzenie napisów w Adobe Premiere. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Automatyczna transkrypcja nagrań w praktycznie każdym języku i tworzenie napisów w Adobe Premiere. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploSubs automatycznie rozpoznaje mowę i generuje napisy do montowanego filmu. W przeciwieństwie do standardowej transkrypcji Adobe Premiere, która obsługuje ograniczoną listę języków, ExploSubs wykorzystuje wielojęzyczny model rozpoznawania mowy obsługujący bardzo szeroki zakres języków z całego świata. Plugin obsługuje osobne ścieżki audio i pozwala tworzyć napisy na podstawie konkretnych tracków. Przy ponownej transkrypcji może wykorzystać wcześniej wyeksportowane audio, dzięki czemu nie trzeba wykonywać całego procesu od początku. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploSubs - plugin do Adobe Premiere', imagePlaceholder: 'ExploSubs', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'explomatch', slug: 'explomatch-plugin-do-adobe-premiere', name: '(Wkrótce) ExploMatch - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Automatyczne dopasowywanie kolorystyki ujęć z różnych kamer. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Automatyczne dopasowywanie kolorystyki ujęć z różnych kamer. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploMatch analizuje ujęcia i automatycznie dopasowuje ich wygląd za pomocą parametrów Lumetri Color. Może korygować między innymi temperaturę, tint, ekspozycję, kontrast, światła, cienie, biele, czernie oraz saturację. Ułatwia uzyskanie spójnego obrazu podczas montażu materiałów nagrywanych różnymi kamerami. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploMatch - plugin do Adobe Premiere', imagePlaceholder: 'ExploMatch', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'exploimport', slug: 'exploimport-plugin-do-adobe-premiere', name: '(Wkrótce) ExploImport - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Automatyczne rozpoznawanie kamer i rozmieszczanie materiałów na timeline. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Automatyczne rozpoznawanie kamer i rozmieszczanie materiałów na timeline. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploImport analizuje importowane materiały, rozpoznaje urządzenia na podstawie nazw plików oraz parametrów nagrania i automatycznie rozmieszcza je na odpowiednich ścieżkach timeline. Ułatwia przygotowanie projektu zawierającego materiały z wielu kamer, takich jak DJI Action, DJI Pocket, GoPro, Lumix czy dron. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploImport - plugin do Adobe Premiere', imagePlaceholder: 'ExploImport', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'exploselect', slug: 'exploselect-plugin-do-adobe-premiere', name: '(Wkrótce) ExploSelect - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Błyskawiczne odnajdywanie na timeline klipów wybranych w Project Media. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Błyskawiczne odnajdywanie na timeline klipów wybranych w Project Media. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploSelect pozwala zaznaczyć wiele materiałów w panelu Project Media, a następnie jednym kliknięciem odnaleźć i zaznaczyć odpowiadające im klipy znajdujące się na timeline. Przydatne szczególnie w dużych projektach, gdzie ręczne wyszukiwanie konkretnych materiałów zajmuje dużo czasu. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploSelect - plugin do Adobe Premiere', imagePlaceholder: 'ExploSelect', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'explozoom', slug: 'explozoom-plugin-do-adobe-premiere', name: '(Wkrótce) ExploZoom - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Automatyczne tworzenie płynnych zoomów za pomocą efektu Transform. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Automatyczne tworzenie płynnych zoomów za pomocą efektu Transform. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: "ExploZoom automatyzuje tworzenie płynnego efektu przybliżenia bez konieczności ręcznego ustawiania keyframe'ów. Plugin wykorzystuje efekt Transform i pozwala kontrolować szybkość zoomu, zachowując spójne tempo niezależnie od długości klipu. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.",
    sizes: [], images: [], image: '', imageAlt: 'ExploZoom - plugin do Adobe Premiere', imagePlaceholder: 'ExploZoom', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'exploloud', slug: 'exploloud-plugin-do-adobe-premiere', name: '(Wkrótce) ExploLoud - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Inteligentna normalizacja głośności i automatyczne wyrównywanie mowy. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Inteligentna normalizacja głośności i automatyczne wyrównywanie mowy. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploLoud analizuje dźwięk poszczególnych klipów i automatycznie dostosowuje ich poziom głośności. Rozpoznaje mowę, uwzględnia różnice pomiędzy nagraniami i pomaga uzyskać równy poziom dialogów w całym filmie. Dzięki temu ogranicza konieczność ręcznego poprawiania głośności każdego klipu i przyspiesza przygotowanie audio do gotowego filmu. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploLoud - plugin do Adobe Premiere', imagePlaceholder: 'ExploLoud', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
  {
    id: 'explofx', slug: 'explofx-plugin-do-adobe-premiere', name: '(Wkrótce) ExploFX - Plugin do Adobe Premiere', price: 45, available: false,
    summary: 'Szybkie nakładanie efektów i presetów bezpośrednio z jednego panelu. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    description: 'Szybkie nakładanie efektów i presetów bezpośrednio z jednego panelu. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    longDescription: 'ExploFX usprawnia korzystanie z efektów podczas montażu w Adobe Premiere. Pozwala szybko wybierać i nakładać efekty oraz obsługiwane presety na zaznaczone klipy bez ciągłego wyszukiwania ich w standardowym panelu Effects. Interfejs został zaprojektowany tak, aby zajmował mało miejsca i pasował do środowiska Premiere. Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
    sizes: [], images: [], image: '', imageAlt: 'ExploFX - plugin do Adobe Premiere', imagePlaceholder: 'ExploFX', imageCaption: 'Plugin do Adobe Premiere — wkrótce.', note: 'Plugin nie jest jeszcze gotowy i będzie dostępny wkrótce.',
  },
];

// Jak dodać nowy produkt?
// 1. Skopiuj jeden z powyższych obiektów i nadaj mu unikalne id oraz slug.
// 2. Uzupełnij nazwę, cenę, opis i ewentualne rozmiary.
// 3. (Opcjonalnie) Dodaj tablicę longDescription ze szczegółowym opisem – każdy element to nowa linia na stronie produktu.
// 4. (Opcjonalnie) podaj ścieżkę do zdjęcia w polu "image" lub zostaw puste, aby wyświetlić placeholder.
// 5. Zapisz plik i dodaj stronę produktu jako kopię istniejącej (np. t-shirt-meski-classic.html) z nowym slugiem.
